export const FETCH_TODOS = 'FETCH_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNUP = 'USER_SIGNUP'
